basePath: /
host: 188.93.210.165:8080
info:
  contact: {}
  description: API Server for Regulations
  title: Regulations API
  version: "1.0"
paths:
  /api/heartbeat:
    get:
      responses:
        "204":
          description: ""
        "400":
          description: ""
      summary: Heartbeat metric
      tags:
      - metric
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
