-- MySQL Script generated by MySQL Workbench
-- Вс 26 июн 2022 15:48:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema doc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema doc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doc` ;
USE `doc` ;

-- -----------------------------------------------------
-- Table `doc`.`doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doc`.`doc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `abbreviation` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doc`.`chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doc`.`chapter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `num` VARCHAR(15) NULL DEFAULT NULL,
  `doc_id` INT NOT NULL,
  PRIMARY KEY (`id`, `doc_id`),
  INDEX `fk_chapter_doc1_idx` (`doc_id` ASC) VISIBLE,
  CONSTRAINT `fk_chapter_doc1`
    FOREIGN KEY (`doc_id`)
    REFERENCES `doc`.`doc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doc`.`paragraph`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doc`.`paragraph` (
  `id` INT NOT NULL,
  `text` VARCHAR(45) NULL DEFAULT NULL,
  `edited_text` VARCHAR(45) NULL DEFAULT NULL,
  `chapter_id` INT NOT NULL,
  PRIMARY KEY (`id`, `chapter_id`),
  INDEX `fk_paragraph_chapter_idx` (`chapter_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_paragraph_chapter`
    FOREIGN KEY (`chapter_id`)
    REFERENCES `doc`.`chapter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doc`.`paragraph_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doc`.`paragraph_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `num` VARCHAR(45) NOT NULL,
  `img` LONGBLOB NOT NULL,
  `paragraph_id` INT NOT NULL,
  PRIMARY KEY (`id`, `paragraph_id`),
  INDEX `fk_paragraph_table_paragraph1_idx` (`paragraph_id` ASC) VISIBLE,
  CONSTRAINT `fk_paragraph_table_paragraph1`
    FOREIGN KEY (`paragraph_id`)
    REFERENCES `doc`.`paragraph` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
